import Testing
import Foundation
@testable import ScarfCore

/// R09 of the Hermes v0.21.5 audit remediation — the chat event pipeline.
///
///  - S02-F2: live tool cards for built-in tools. Hermes sends `rawInput`
///    only for unknown/plugin tools; the target lives in `title` and
///    `locations` (`acp_adapter/tools.py:797-815` @ v2026.9.24).
///  - S02-F4: `messageId` segments replies, so an id-less mid-turn status
///    line is not glued to the resumed turn's text.
///  - S02-F1: a local user echo is reconciled with state.db by the WIRE
///    text and its send position, never by the typed text.
///
/// Wire fixtures are the exact JSON Hermes v2026.9.24 emits: generated by
/// running `acp_adapter.tools.build_tool_start` / `acp.update_agent_message_text`
/// from the tagged tree's own venv and dumping with `by_alias=True,
/// exclude_none=True`. Stored-row strings come from the same tree
/// (`_durable_content`, `steer_user_row`, `_attach_interrupted_prompt`).
@Suite struct ChatEventPipelineV0215Tests {

    // MARK: - Helpers

    private static func parse(_ updateJSON: String) -> ACPEvent? {
        let json = #"{"jsonrpc":"2.0","method":"session/update","params":"# + updateJSON + "}"
        guard let raw = try? JSONDecoder().decode(ACPRawMessage.self, from: Data(json.utf8)) else {
            Issue.record("failed to decode ACPRawMessage fixture")
            return nil
        }
        return ACPEventParser.parse(notification: raw)
    }

    private static func toolStart(_ updateJSON: String) -> ACPToolCallEvent? {
        guard case .toolCallStart(_, let call)? = parse(updateJSON) else {
            Issue.record("expected .toolCallStart")
            return nil
        }
        return call
    }

    // Exact `tool_call` / `tool_call_update` notifications (params only).
    private static let readA = #"{"sessionId": "s", "update": {"kind": "read", "locations": [{"path": "Sources/a.swift"}], "title": "read_file: a.swift", "toolCallId": "tc-aaaaaaaaaaaa", "sessionUpdate": "tool_call"}}"#
    private static let readB = #"{"sessionId": "s", "update": {"kind": "read", "locations": [{"path": "Sources/b.swift"}], "title": "read_file: b.swift", "toolCallId": "tc-bbbbbbbbbbbb", "sessionUpdate": "tool_call"}}"#
    private static let terminal = #"{"sessionId": "s", "update": {"content": [{"content": {"text": "$ swift test --filter Foo", "type": "text"}, "type": "content"}], "kind": "execute", "locations": [], "title": "terminal: swift test --filter Foo", "toolCallId": "tc-cccccccccccc", "sessionUpdate": "tool_call"}}"#
    private static let plugin = #"{"sessionId": "s", "update": {"content": [{"content": {"text": "{\n  \"q\": \"x\"\n}", "type": "text"}, "type": "content"}], "kind": "other", "locations": [], "rawInput": {"q": "x"}, "title": "my_plugin_tool", "toolCallId": "tc-dddddddddddd", "sessionUpdate": "tool_call"}}"#

    private static func complete(_ id: String) -> String {
        #"{"sessionId": "s", "update": {"content": [{"content": {"text": "Read file\n\n```\nhi\n```", "type": "text"}, "type": "content"}], "kind": "read", "status": "completed", "toolCallId": ""# + id + #"", "sessionUpdate": "tool_call_update"}}"#
    }

    @MainActor
    private static func engagedVM() -> RichChatViewModel {
        let vm = RichChatViewModel(context: .local)
        vm.setSessionId("s")
        vm.addUserMessage(text: "go")
        return vm
    }

    @MainActor
    private static func liveSegment(_ vm: RichChatViewModel) -> MessageGroup.ChatActivitySegment? {
        for group in vm.messageGroups.reversed() {
            for item in group.transcriptItems(coalesceText: true).reversed() {
                if case .activity(let seg) = item { return seg }
            }
        }
        return nil
    }

    // MARK: - S02-F2 parser

    @Test func builtInToolStartCarriesLocationButNoArguments() throws {
        let call = try #require(Self.toolStart(Self.readA))
        #expect(call.rawInput == nil)
        #expect(call.argumentsJSON == "{}")
        #expect(call.functionName == "read_file")
        #expect(call.locationPaths == ["Sources/a.swift"])
        // The full path beats the title's basename preview.
        #expect(call.livePreview == "Sources/a.swift")
    }

    @Test func terminalStartFallsBackToTheTitlePreview() throws {
        let call = try #require(Self.toolStart(Self.terminal))
        #expect(call.locationPaths.isEmpty)
        #expect(call.livePreview == "swift test --filter Foo")
    }

    @Test func pluginToolStillCarriesRawInput() throws {
        let call = try #require(Self.toolStart(Self.plugin))
        #expect(call.rawInput?["q"] as? String == "x")
        // Bare-name title, no location → nothing to preview.
        #expect(call.livePreview == nil)
    }

    // MARK: - S02-F2 live transcript

    /// The audit's failure scenario: three reads of different files used to
    /// collapse into one "read_file ×3" card with no path.
    @Test @MainActor func consecutiveReadsOfDifferentFilesStaySeparateCards() throws {
        let vm = Self.engagedVM()
        let readC = Self.readB
            .replacingOccurrences(of: "b.swift", with: "c.swift")
            .replacingOccurrences(of: "tc-bbbbbbbbbbbb", with: "tc-eeeeeeeeeeee")
        for (start, id) in [(Self.readA, "tc-aaaaaaaaaaaa"), (Self.readB, "tc-bbbbbbbbbbbb"), (readC, "tc-eeeeeeeeeeee")] {
            vm.handleACPEvent(try #require(Self.parse(start)))
            vm.handleACPEvent(try #require(Self.parse(Self.complete(id))))
        }
        let seg = try #require(Self.liveSegment(vm))
        #expect(seg.totalToolCount == 3)
        #expect(seg.entries.count == 3)
        #expect(seg.entries.map(\.count) == [1, 1, 1])
        #expect(seg.entries.map(\.call.argumentsSummary) == ["Sources/a.swift", "Sources/b.swift", "Sources/c.swift"])
        // Inspector input: still the honest "{}" for arguments, with the
        // preview carried alongside.
        #expect(seg.entries.allSatisfy { $0.call.hasNoArguments })
    }

    /// Genuine repeats (same tool, same target) still collapse.
    @Test @MainActor func repeatedReadOfTheSameFileStillCollapses() throws {
        let vm = Self.engagedVM()
        let again = Self.readA.replacingOccurrences(of: "tc-aaaaaaaaaaaa", with: "tc-ffffffffffff")
        vm.handleACPEvent(try #require(Self.parse(Self.readA)))
        vm.handleACPEvent(try #require(Self.parse(Self.complete("tc-aaaaaaaaaaaa"))))
        vm.handleACPEvent(try #require(Self.parse(again)))
        vm.handleACPEvent(try #require(Self.parse(Self.complete("tc-ffffffffffff"))))
        let seg = try #require(Self.liveSegment(vm))
        #expect(seg.entries.count == 1)
        #expect(seg.entries.first?.count == 2)
    }

    /// A call reloaded from state.db has real arguments and no preview; the
    /// summary still comes from the arguments.
    @Test func storedCallSummaryIgnoresMissingPreview() {
        let stored = HermesToolCall(callId: "c1", functionName: "read_file", arguments: #"{"path":"Sources/a.swift"}"#)
        #expect(stored.livePreview == nil)
        #expect(stored.argumentsSummary == "Sources/a.swift")
        let live = HermesToolCall(callId: "c2", functionName: "read_file", arguments: "{}", livePreview: "Sources/a.swift")
        #expect(live.argumentsSummary == "Sources/a.swift")
        let bare = HermesToolCall(callId: "c3", functionName: "todo", arguments: "{}")
        #expect(bare.argumentsSummary == "")
    }

    // MARK: - S02-F4 messageId

    private static let streamedChunk = #"{"sessionId": "s", "update": {"content": {"text": "Working on it", "type": "text"}, "messageId": "3f1c2a9e-8b7d-4c6e-9a51-2d0f4b7e6c13", "sessionUpdate": "agent_message_chunk"}}"#
    private static let steerStatus = #"{"sessionId": "s", "update": {"content": {"text": "⏩ Steer queued for the active turn: be brief", "type": "text"}, "sessionUpdate": "agent_message_chunk"}}"#
    private static let resumedChunk = #"{"sessionId": "s", "update": {"content": {"text": "OK, keeping it short.", "type": "text"}, "messageId": "3f1c2a9e-8b7d-4c6e-9a51-2d0f4b7e6c13", "sessionUpdate": "agent_message_chunk"}}"#
    private static let thought = #"{"sessionId": "s", "update": {"content": {"text": "thinking", "type": "text"}, "messageId": "3f1c2a9e-8b7d-4c6e-9a51-2d0f4b7e6c13", "sessionUpdate": "agent_thought_chunk"}}"#

    @Test func chunkParsingCarriesMessageId() {
        guard case .messageChunk(_, _, _, _, let id)? = Self.parse(Self.streamedChunk) else {
            Issue.record("expected .messageChunk"); return
        }
        #expect(id == "3f1c2a9e-8b7d-4c6e-9a51-2d0f4b7e6c13")
        guard case .messageChunk(_, _, _, _, let none)? = Self.parse(Self.steerStatus) else {
            Issue.record("expected .messageChunk"); return
        }
        #expect(none == nil)
        guard case .thoughtChunk(_, _, let thoughtId)? = Self.parse(Self.thought) else {
            Issue.record("expected .thoughtChunk"); return
        }
        #expect(thoughtId == "3f1c2a9e-8b7d-4c6e-9a51-2d0f4b7e6c13")
    }

    /// The audit's failure scenario: `/steer be brief` mid-stream used to
    /// render "⏩ Steer queued for the active turn: be briefOK, keeping it
    /// short."
    @Test @MainActor func steerStatusLineIsItsOwnBubble() throws {
        let vm = Self.engagedVM()
        vm.handleACPEvent(try #require(Self.parse(Self.streamedChunk)))
        vm.addUserMessage(text: "/steer be brief")
        vm.handleACPEvent(try #require(Self.parse(Self.steerStatus)))
        vm.handleACPEvent(try #require(Self.parse(Self.resumedChunk)))
        vm.handleACPEvent(.promptComplete(sessionId: "s", response: ACPPromptResult(
            stopReason: "end_turn", inputTokens: 1, outputTokens: 1, thoughtTokens: 0, cachedReadTokens: 0
        )))
        let assistants = vm.messages.filter(\.isAssistant).map(\.content)
        #expect(assistants == [
            "Working on it",
            "⏩ Steer queued for the active turn: be brief",
            "OK, keeping it short."
        ])
    }

    /// C1: a host that never sends `messageId` keeps one buffer per turn —
    /// chunks append exactly as before.
    @Test @MainActor func hostWithoutMessageIdsStillAppends() {
        let vm = Self.engagedVM()
        vm.handleACPEvent(.messageChunk(sessionId: "s", text: "Hello "))
        vm.handleACPEvent(.messageChunk(sessionId: "s", text: "there"))
        vm.handleACPEvent(.promptComplete(sessionId: "s", response: ACPPromptResult(
            stopReason: "end_turn", inputTokens: 1, outputTokens: 1, thoughtTokens: 0, cachedReadTokens: 0
        )))
        #expect(vm.messages.filter(\.isAssistant).map(\.content) == ["Hello there"])
    }

    /// A normal multi-round turn (thought → tool → thought → answer) must
    /// render exactly as on a host without ids: Hermes closes the id before
    /// each tool round, but the tool completion already finalized the
    /// bubble, so the id change adds no extra split — and the turn clock
    /// (`turnDurations`) is recorded the same number of times.
    @Test @MainActor func multiRoundTurnRendersTheSameWithAndWithoutIds() throws {
        func run(ids: Bool) throws -> (rows: [String], durations: Int) {
            let vm = Self.engagedVM()
            vm.handleACPEvent(.thoughtChunk(sessionId: "s", text: "plan", messageId: ids ? "a" : nil))
            vm.handleACPEvent(try #require(Self.parse(Self.readA)))
            vm.handleACPEvent(try #require(Self.parse(Self.complete("tc-aaaaaaaaaaaa"))))
            vm.handleACPEvent(.thoughtChunk(sessionId: "s", text: "more", messageId: ids ? "b" : nil))
            vm.handleACPEvent(.messageChunk(sessionId: "s", text: "Answer", messageId: ids ? "b" : nil))
            vm.handleACPEvent(.promptComplete(sessionId: "s", response: ACPPromptResult(
                stopReason: "end_turn", inputTokens: 1, outputTokens: 1, thoughtTokens: 0, cachedReadTokens: 0
            )))
            let rows = vm.messages.filter(\.isAssistant).map { "\($0.content)|\($0.reasoning ?? "")|\($0.toolCalls.count)" }
            return (rows, vm.turnDurations.count)
        }
        let withIds = try run(ids: true)
        let without = try run(ids: false)
        #expect(withIds.rows == without.rows)
        #expect(withIds.durations == without.durations)
        #expect(withIds.rows == ["|plan|1", "Answer|more|0"])
    }

    /// A reply's thoughts and its text share one id: one message.
    @Test @MainActor func thoughtAndTextOfOneReplyStayTogether() throws {
        let vm = Self.engagedVM()
        vm.handleACPEvent(try #require(Self.parse(Self.thought)))
        vm.handleACPEvent(try #require(Self.parse(Self.streamedChunk)))
        vm.handleACPEvent(.promptComplete(sessionId: "s", response: ACPPromptResult(
            stopReason: "end_turn", inputTokens: 1, outputTokens: 1, thoughtTokens: 0, cachedReadTokens: 0
        )))
        let assistants = vm.messages.filter(\.isAssistant)
        #expect(assistants.count == 1)
        #expect(assistants.first?.content == "Working on it")
        #expect(assistants.first?.reasoning == "thinking")
    }

    // MARK: - S02-F1 keys (pure)

    private static let roster: Set<String> = ["help", "model", "tools", "context", "reset", "compress", "steer", "queue", "version"]

    @Test func keysFollowTheWireNotTheTypedText() {
        let keys = RichChatViewModel.persistedUserRowKeys
        // /scarf-* expansion: the expanded body is what Hermes stores.
        #expect(keys("Summarise the project.", 0, Self.roster) == ["Summarise the project."])
        // Idle /queue fallback sends the argument only.
        #expect(keys("foo", 0, Self.roster) == ["foo"])
        // Dispatched commands: no row…
        #expect(keys("/help", 0, Self.roster) == [])
        #expect(keys("/model gpt-5", 0, Self.roster) == [])
        #expect(keys("/Compress", 0, Self.roster) == [])
        // …except /steer and /queue, whose argument lands later.
        #expect(keys("/steer be brief", 0, Self.roster) == ["be brief"])
        #expect(keys("/queue  next thing ", 0, Self.roster) == ["next thing"])
        #expect(keys("/queue", 0, Self.roster) == [])
        // Unknown slash names go to the model verbatim.
        #expect(keys("/goal ship it", 0, Self.roster) == ["/goal ship it"])
        // With an image a slash prompt goes to the agent too.
        #expect(keys("/help", 1, Self.roster) == ["/help"])
        // Image-only.
        #expect(keys("", 2, Self.roster) == ["[screenshot]", "[Image attachment]"])
        #expect(keys("  ", 0, Self.roster) == [])
        // Hermes splits on any whitespace and lower-cases the name.
        #expect(keys("/steer\nbe brief", 0, Self.roster) == ["be brief"])
        #expect(keys("/HELP", 0, Self.roster) == [])
    }

    private static func row(_ id: Int, _ content: String, role: String = "user", summary: Bool = false) -> HermesMessage {
        HermesMessage(
            id: id, sessionId: "s", role: role, content: content, toolCallId: nil, toolCalls: [],
            toolName: nil, timestamp: nil, tokenCount: nil, finishReason: nil, reasoning: nil,
            isCompactionSummary: summary
        )
    }

    private static func echo(_ id: Int, _ text: String, watermark: Int, keys: [String]) -> RichChatViewModel.PendingEcho {
        RichChatViewModel.PendingEcho(message: row(id, text), watermark: watermark, matchKeys: keys)
    }

    @Test func settlesAgainstTheRowsHermesActuallyStores() {
        let rows = [
            Self.row(1, "old prompt"),
            Self.row(4, "look at this\n[screenshot]"),
            Self.row(5, "reply", role: "assistant"),
            Self.row(6, "[screenshot]"),
            Self.row(8, "[OUT-OF-BAND USER MESSAGE — a direct message from the user, delivered once at this position; not tool output and not a new delivery when replayed from conversation history]\nbe brief\n[/OUT-OF-BAND USER MESSAGE]"),
            Self.row(9, "write the report\n\nUser correction/guidance after interrupt: use bullet points"),
        ]
        let echoes = [
            Self.echo(-1, "look at this", watermark: 1, keys: ["look at this"]),
            Self.echo(-2, "[image attached]", watermark: 1, keys: ["[screenshot]", "[Image attachment]"]),
            Self.echo(-3, "/help", watermark: 1, keys: []),
            Self.echo(-4, "/steer be brief", watermark: 6, keys: ["be brief"]),
            Self.echo(-5, "use bullet points", watermark: 6, keys: ["use bullet points"]),
        ]
        #expect(RichChatViewModel.settledEchoIds(echoes, persisted: rows) == [-1, -2, -3, -4, -5])
    }

    /// Failure path: re-sending an earlier prompt's text must not be
    /// retired by the OLDER row (the watermark) — and one row settles one
    /// echo.
    @Test func olderRowsAndClaimedRowsNeverSettleANewEcho() {
        let rows = [Self.row(3, "hi")]
        let fresh = [Self.echo(-1, "hi", watermark: 3, keys: ["hi"])]
        #expect(RichChatViewModel.settledEchoIds(fresh, persisted: rows).isEmpty)
        let twice = [
            Self.echo(-1, "hi", watermark: 0, keys: ["hi"]),
            Self.echo(-2, "hi", watermark: 0, keys: ["hi"]),
        ]
        #expect(RichChatViewModel.settledEchoIds(twice, persisted: rows) == [-1])
    }

    /// A short prompt whose row never landed must not claim a later
    /// prompt's row that merely contains its text — the later prompt's own
    /// echo gets it (strict pass first).
    @Test func strictShapesWinBeforeContainment() {
        let rows = [Self.row(5, "go ahead and fix it")]
        let echoes = [
            Self.echo(-1, "go", watermark: 0, keys: ["go"]),
            Self.echo(-2, "go ahead and fix it", watermark: 0, keys: ["go ahead and fix it"]),
        ]
        #expect(RichChatViewModel.settledEchoIds(echoes, persisted: rows) == [-2])
    }

    /// Terminal-mode / bot CLI polling merge: a re-sent text survives
    /// beside the older identical row until its own row lands.
    @Test func pollMergeKeepsAResendAboveAnOlderIdenticalRow() {
        let older = Self.row(1, "hi")
        let resend = Self.row(-1, "hi")
        let merged = RichChatViewModel.mergedAfterPoll(fetched: [older], currentLocal: [older, resend])
        #expect(merged.filter(\.isUser).map(\.id).sorted() == [-1, 1])
        let landed = RichChatViewModel.mergedAfterPoll(fetched: [older, Self.row(2, "hi")], currentLocal: [older, resend])
        #expect(landed.filter(\.isUser).map(\.id).sorted() == [1, 2])
    }

    /// A standalone compaction summary is a Hermes-authored user-role row;
    /// it never stands in for the user's prompt.
    @Test func compactionSummaryRowNeverSettlesAnEcho() {
        let rows = [Self.row(7, "[CONTEXT COMPACTION — REFERENCE ONLY] … hi …", summary: true)]
        let echoes = [Self.echo(-1, "hi", watermark: 0, keys: ["hi"])]
        #expect(RichChatViewModel.settledEchoIds(echoes, persisted: rows).isEmpty)
    }
}
